sprite $aristacvp [48x48/16z] {
xLG7aYGn26kJaV__toiSYisxbIzfCbORINZw-ID0ecQcF7v27XB0B22DlwLpO3RWt_HGpDV8BrjOq-7gg4_v6LrkDtpQWPi-OrLYIVh4myZv8N_Q9rwRZLWY
w0HBRtScPgPejf3vC-YMzFKuBR5GpCHC8Stfd33AAwwXsQBf6QeaMQbOXSHeGUypv9vmKgwATAIl1jh1sPOiM2LQ1BkHqliCVIlmKrjVW92jfjcf9ECEpUds
zHjIZ3kYbOoLpNHTH4WFeqAw5z1ciZkpOtlM9Jiw1UMSPyw2CsqoN1ErdVLHMgcgE6eNmGqHlQeJxFDj3hOwNVvWiS29q9Va2y3kMRBowqNtK2PYzGHuvm0W
mrMOnZszLc4ZH6DdRCB4lFqKaPZ5FBmkAAjwT3UGliyAgtaazhBp6ZEu1zRmL_wl1voL4LtjVowzhVOf7OwtzV0LpsTt5WdCRu7ZQuUlzZ6ghWMXvr_7V_p7
Bm
}

sprite $netbox [48x48/16z] {
xTH7TiCm34LHDABiVyEXa1vynlPSrrKyJxqGS1DbWbXLQV2g54BCrCOCMfaL1CYL6_snAZS2UDU7vJiXr-9bRdvcC45gF7DdeGCnaDEP_5r-m5nCGM--yD8r
gtniZrSF0v6RhyrZVScBqiHvgPRrfGUxHqUuL3PR_TFwk1F2aMdpUAuC9epHyUHQT89xVwQ_U-PZRigZ_nYTk9yF_4dA-yTKJS_FXoyhmxOUWZttakG3QphB
jclSzxBnzkDSc0aTJpxar6R_V_xuUcRXcTFA84Ximy_1qsDJZT5Je4x7KKrUwJVqrAWWI5IPXXNEz8hR6m
}

sprite $networkfabric [48x48/16z] {
vLG74YCn3382_FyVfsWyrZPDlNwa2eEDbEoE_nI83VHSmNF33VTFwJLjptnJozrDSQMYaQu0nfc1frivB1jdnZ8wVIWKnb6ULASdXv26BOU-R0FXknZ6bdzh
j0txgnbfMF9X9Fs8t4YHXYMFfD36NmeQK2ntsq0kmaY3kOjG4n_byYmbtCTV6f5QthQ1u3v678FQ6pEQ-0bIwQJoiscWJiLSCavKqYkAr9PDrLONrA4YkOEf
eXPEJMMRrVYQ6RluQumrM3KDm4kUoWeXhgEUubCxoKubFZP0bdmmCdCPo8VuLCqsYJBS6p2eenl7Yl2rNL6eaYIxnGJdYO5zAZLvYN-Pc7sPjifhhxkaSsgi
cZdfghyPOXRuT5VcBCJVhnyi8ETHTSuBB8oVZZS
}

